M48
; DRILL file {KiCad (6.0.4)} date Tue Apr 19 13:08:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-19T13:08:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0866
%
G90
G05
T1
X5.3Y-3.8
X5.3Y-3.85
X5.3Y-3.9
X5.6Y-3.8
X5.6Y-3.85
X5.6Y-3.9
T2
X4.7Y-3.6
X4.7Y-3.8
X5.0Y-3.6
X5.0Y-3.8
T3
X4.4958Y-3.9548
X4.5Y-3.6
X4.5Y-3.7
X4.5958Y-3.9548
X4.6958Y-3.9548
X5.3Y-3.6
X5.4Y-3.6
T4
X5.1Y-4.0
X5.7Y-3.5
T0
M30
