M48
; DRILL file {KiCad (6.0.4)} date Sun Oct  2 23:44:45 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-02T23:44:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
%
G90
G05
T1
X5.7092Y-3.8976
X5.7092Y-3.9976
X5.7592Y-3.9476
T2
X4.95Y-3.7
X4.95Y-4.0
X5.2Y-3.7
X5.2Y-4.0
X5.4Y-3.7
X5.4Y-4.0
T3
X5.0Y-4.2
X5.0Y-4.3
X5.4Y-4.2
X5.4Y-4.3
X5.8Y-4.2
X5.8Y-4.3
T4
X4.6722Y-3.8994
X4.6722Y-3.9994
X4.6722Y-4.0994
X5.6Y-3.7
X5.7Y-3.7
T0
M30
